portfolio_local_dev:
  hosts:
    gitea:
      ansible_host: localhost
      ansible_port: 2223
    action_runner:
      ansible_host: localhost
      ansible_port: 2224
    conan:
      ansible_host: localhost
      ansible_port: 2225

portfolio_cloud_prod:
  hosts: # Should be retrieved from cloud hosts through APIs or dedicated ansible roles
    gitea:
    action_runner:
    conan:
