- name: Get init process name
  hosts: portfolio_local_dev
  tasks:
    - name: Get init process name
      init_process_facts:

- name: Gitea personnal instance
  hosts: gitea
  become: true
  become_method: ansible.builtin.sudo
  vars_files:
    - variables/dev.yaml
  roles:
    - gitea

- name: Gitea action runner
  hosts: act_runner-gitea
  become: true
  become_method: ansible.builtin.sudo
  vars:
    go_package: go1.24.0.linux-amd64.tar.gz
  vars_files:
    - variables/dev.yaml
  roles:
    - go
    - role: act_runner
      vars:
        act_runner_gitea_host: http://containers-gitea-1:3000/
        act_runner_registration_token: "{{ hostvars['gitea'].act_runner_token.content | b64decode }}"

- name: Nginx reverse proxy
  hosts: nginx-reverse-proxy
  become: true
  become_method: ansible.builtin.sudo
  roles:
    - role: nginx-reverse-proxy
      vars:
        nginx_upstreams:
          - { name: gitea, host: localhost, port: 80, upstream: containers-gitea-1:3000 }
