- name: Get init process name
  hosts: portfolio_local_dev
  tasks:
    - name: Get init process name
      init_process_facts:

- name: "Gitea personnal instance"
  hosts: gitea
  become: true
  become_method: sudo
  vars_files:
    - variables/dev.yaml
  roles:
    - gitea


- name: "Gitea action runner"
  hosts: act_runner-gitea
  become: true
  become_method: sudo
  vars:
    go_package: go1.24.0.linux-amd64.tar.gz
  vars_files:
    - variables/dev.yaml
  roles:
    - go
    - role: act_runner
      vars:
        gitea_host: http://containers-gitea-1:3000/
        action_runner_token: "{{ hostvars['gitea'].action_runner_token }}"

