- name: "Gitea personnal instance"
  hosts: gitea
  become: true
  become_method: sudo
  vars_files:
    - variables.yaml

  roles:
    - gitea


- name: "Gitea action runner"
  hosts: act_runner-gitea
  become: true
  become_method: sudo
  vars_files:
    - variables.yaml

  # roles:
  #   - act_runner_gitea
