- name: Get init process name
  hosts: portfolio_local_dev
  tasks:
    - name: Get init process name
      init_process_facts:

- name: "Gitea personnal instance"
  hosts: gitea
  become: true
  become_method: sudo
  vars_files:
    - variables.yaml
  roles:
    - gitea


- name: "Gitea action runner"
  hosts: act_runner-gitea
  become: true
  become_method: sudo
  vars:
    action_runner_token: ""
    gitea_host: containers-gitea-1
    go_package: go1.24.0.linux-amd64.tar.gz
  vars_files:
    - variables.yaml
  roles:
    - go
    - act_runner
