- name: Get init process name
  hosts: portfolio_local_dev
  tasks:
    - name: Get init process name
      init_process_facts:


- name: Mysql gitea database
  hosts: mysql-gitea
  become: true
  become_method: ansible.builtin.sudo
  vars_files:
    - variables.yaml
  roles:
    - role: geerlingguy.mysql
      vars:
        mysql_enabled_on_startup: true
        mysql_databases:
          - name: "{{ gitea_db_name }}"
        mysql_users:
          - name: "{{ gitea_db_user }}"
            password: "{{ gitea_db_password }}"
            host: "{{ gitea_hostname }}"
            encrypted: no
            priv: "{{ gitea_db_name }}.*:ALL"
            state: present

- name: Gitea instance
  hosts: gitea
  become: true
  become_method: ansible.builtin.sudo
  vars_files:
    - variables.yaml
  roles:
    - gitea


- name: Gitea action runner
  hosts: act_runner-gitea
  become: true
  become_method: ansible.builtin.sudo
  vars:
    go_package: go1.24.0.linux-amd64.tar.gz
  vars_files:
    - variables.yaml
  roles:
    - go
    - role: act_runner
      vars:
        act_runner_gitea_host: http://containers-gitea-1:3000/
        act_runner_registration_token: "{{ hostvars['gitea'].act_runner_token.content | b64decode }}"


- name: Nginx reverse proxy
  hosts: nginx-reverse-proxy
  become: true
  become_method: ansible.builtin.sudo
  vars_files:
    - variables.yaml
  roles:
    - role: nginx-reverse-proxy
      vars:
        nginx_upstreams:
          - { name: gitea, host: gitea.zozo.com, port: 80, upstream: "{{ gitea_hostname }}:{{ gitea_http_port }}" }
