- name: Get init process name
  hosts: portfolio_local_dev
  tasks:
    - name: Get info
      init_process_facts:

- name: "Gitea personnal instance"
  hosts: gitea
  become: true
  become_method: sudo
  vars_files:
    - variables.yaml

  roles:
    - gitea


- name: "Gitea action runner"
  hosts: act_runner-gitea
  become: true
  become_method: sudo
  vars:
    go_package: go1.24.0.linux-amd64.tar.gz
  vars_files:
    - variables.yaml

  tasks:
    # Basic compilation tools installation
    - name: install git and make
      ansible.builtin.apt:
        name: 
        - git
        - make
        state: present

    # Go installation
    - name: download go
      ansible.builtin.command:
        creates: /tmp/go1.24.0.linux-amd64.tar.gz
        cmd: "wget -O /tmp/{{ go_package }} https://go.dev/dl/{{ go_package }}"
    - name: extract go
      ansible.builtin.command:
        creates: /usr/local/go
        cmd: "tar -C /usr/local -xzf /tmp/{{ go_package }}"
    - name: check go existence
      environment:
        PATH: "{{ ansible_env.PATH }}:/usr/local/go/bin"
      shell:
        cmd: "go version"
      register: go_version
    - name: ensure go is installed
      ansible.builtin.assert:
        that: "'command not found' not in go_version.stderr" 

    # Act_runner build steps
    - name: download act_runner
      ansible.builtin.command:
        cmd: "git clone https://gitea.com/gitea/act_runner /sources"
        creates: /sources
    - name: checkout latest release
      ansible.builtin.shell:
        chdir: /sources
        cmd: "git checkout $(git describe --tags --abbrev=0)"
    - name: build act_runner
      environment:
        PATH: "{{ ansible_env.PATH }}:/usr/local/go/bin"
      ansible.builtin.shell:
        chdir: /sources
        cmd: make build

    # Act runner configuration
    - name: create act_runner directory layout
      ansible.builtin.shell:
        creates: /etc/act_runner
        cmd: mkdir -p /etc/act_runner
    - name: generate act_runner config
      ansible.builtin.shell:
        chdir: /sources
        creates: /etc/act_runner/config.yaml
        cmd: act_runner genereate-config > /etc/act_runner/config.yaml

  # roles:
  #   - act_runner_gitea
