- name: start dockerd
  ansible.builtin.shell:
    creates: /run/docker.pid
    cmd: dockerd --iptables=false --bridge=none &
  when: ansible_facts.init_process_name != "systemd"

# Basic compilation tools installation
- name: install git and make
  tags: build
  ansible.builtin.apt:
    name: 
    - git
    - make
    state: present

# Act_runner build steps
- name: download act_runner
  tags: download
  block:
  - name: find latest act_runner version
    ansible.builtin.uri:
      url: https://gitea.com/api/v1/repos/gitea/act_runner/tags?page=1&limit=1
      return_content: true
    register: json_response
  
  - name: debug json_response
    ansible.builtin.debug:
      verbosity: 0
      var: json_response
  
  - name: download latest act_runner version
    ansible.builtin.get_url:
      url: "{{ json_response.json[0].tarball_url }}"
      dest: ./act_runner-latest.tar.gz
  
  - name: create sources directory
    ansible.builtin.file:
      path: /sources
      state: directory

- name: unpack and build act_runner
  tags: build
  block:
  - name: extract act_runner archive
    tags: build
    ansible.builtin.unarchive:
      src: ./act_runner-latest.tar.gz
      dest: /sources
      remote_src: yes
  
  - name: build act_runner
    tags: build
    environment:
      PATH: "{{ ansible_env.PATH }}:/usr/local/go/bin"
    community.general.make:
      chdir: /sources/act_runner
      target: build
    register: make_out
    changed_when: make_out.stdout != "" and make_out.stderr != ""

# Act runner configuration
- name: configure act_runner
  tags: conf
  block:
  - name: create act_runner directory layout
    ansible.builtin.shell:
      creates: "{{ item }}"
      cmd: "mkdir -p {{ item }}"
    loop:
      - /etc/act_runner
      - /var/lib/act_runner
  
  - name: generate act_runner config
    ansible.builtin.shell:
      chdir: /sources/act_runner
      creates: /etc/act_runner/config.yaml
      cmd: ./act_runner generate-config > /etc/act_runner/config.yaml
  
  - name: register act runner to gitea server
    ansible.builtin.shell:
      creates: /var/lib/act_runner/.runner
      chdir: /var/lib/act_runner
      cmd: "/sources/act_runner/act_runner --config /etc/act_runner/config.yaml register --no-interactive --instance {{ gitea_host }} --token {{ action_runner_token }}"
    register: registration_out

- name: start act_runner
  ansible.builtin.shell:
    chdir: /var/lib/act_runner
    cmd: /sources/act_runner/act_runner --config /etc/act_runner/config.yaml daemon &

