---
# Upstream proxied for.
# DO NOT NAME AN UPSTREAM DEFAULT
# IT WILL BE REMOVED AND RE-APPLIED AT EVERY RUN
# LEADING TO A USELESS NGINX RESTART
nginx_reverse_proxy_upstreams:
  - name: example
    host: localhost
    port: 80
    upstream: localhost:3000
