- name: install git and gitea
  tags: install
  block:
  - name: "Install git"
    ansible.builtin.apt:
      name: git
      state: present
  
  - name: create gitea user and group
    ansible.builtin.user:
      name: git
      shell: /sbin/nologin
      system: true
      create_home: false
      expires: -1
  
  - name: deploy gitea binary and directories
    ansible.builtin.script:
      cmd: gitea_install.sh
      creates: /usr/bin/gitea
    notify:
      - restart gitea

- name: configure gitea
  tags: conf
  block:
  - name: install gitea configuration
    ansible.builtin.template:
      src: app.ini.j2
      dest: /etc/gitea/app.ini
      owner: git
      group: git
      mode: '0600'
    notify:
      - restart gitea
  
  - name: set up gitea service
    ansible.builtin.copy:
      src: gitea.service
      dest: /etc/systemd/system/gitea.service
      owner: root
      group: root
      mode: '0600'
    notify:
      - restart gitea

- name: configure action runner token
  tags:
    - conf
    - actions
  block:
    - name: generate action runner token
      ansible.builtin.shell:
        creates: /etc/gitea/action_token
        cmd: "su git -s /bin/sh -c '/usr/bin/gitea --config /etc/gitea/app.ini actions generate-runner-token' > /etc/gitea/action_token"

    - name: retrieve action runner token
      ansible.builtin.shell:
        cmd: "cat /etc/gitea/action_token"
      changed_when: false
      register: token

    - name: export action runner token
      ansible.builtin.set_fact:
        action_runner_token: "{{ token.stdout }}"
