- name: "Install git"
  tags: install
  ansible.builtin.apt:
    name: git
    state: present

- name: "Create gitea user and group"
  tags: install
  ansible.builtin.user:
    name: git
    shell: /sbin/nologin
    system: true
    create_home: false
    expires: -1

- name: "Deploy gitea binary and directories"
  tags: install
  ansible.builtin.script:
    cmd: gitea_install.sh
    creates: /usr/bin/gitea
  notify:
    - restart gitea

- name: "Install gitea configuration"
  tags: conf
  ansible.builtin.template:
    src: app.ini.j2
    dest: /etc/gitea/app.ini
    owner: git
    group: git
    mode: '0600'
  notify:
    - restart gitea

- name: "Set up gitea service"
  tags: conf
  ansible.builtin.copy:
    src: gitea.service
    dest: /etc/systemd/system/gitea.service
    owner: root
    group: root
    mode: '0600'
  notify:
    - restart gitea
