- name: "Install git"
  ansible.builtin.apt:
    name: git
    state: present

- name: "Create gitea user and group"
  ansible.builtin.user:
    name: git
    shell: /sbin/nologin
    system: true
    create_home: false
    expires: -1

- name: "Deploy gitea binary and directories"
  ansible.builtin.script: gitea_install.sh
  notify:
    - Restart gitea

- name: "Install gitea configuration"
  ansible.builtin.template:
    src: app.ini.j2
    dest: /etc/gitea/app.ini
    owner: git
    group: git
    mode: '0600'
  notify:
    - Restart gitea

- name: "Set up gitea service"
  ansible.builtin.copy:
    src: gitea.service
    dest: /etc/systemd/system/gitea.service
    owner: root
    group: root
    mode: '0600'
  notify:
    - Restart gitea
