---
- name: Stop nginx
  ansible.builtin.command:
    cmd: nginx -s quit
    removes: /run/nginx.pid

- name: Start nginx
  tags: start
  ansible.builtin.shell:
    cmd: nginx -g 'daemon on; master_process on;'
    creates: /run/nginx.pid
