---
- name: Download go
  ansible.builtin.get_url:
    dest: "/tmp/{{ go_package }}.tar.gz"
    url: "https://go.dev/dl/{{ go_package }}"
    owner: root
    group: root
    mode: "0600"

- name: Extract go
  ansible.builtin.unarchive:
    creates: /usr/local/go
    src: "/tmp/{{ go_package }}.tar.gz"
    remote_src: true
    dest: /usr/local
    owner: root
    group: root
    mode: "0700"
