internal_token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYmYiOjE3MzcxMTM5NTB9.1wWMbNghQ8t4afAYO7q68hnHTih5tVAq__JOMt0oPkU"
jwt_secret: "Bw91F_0K-2n9ZZFRax1WT6hvumc5qk5uAFrwfFSZsSw"
lfs_jwt_secret: "Jus8wLu5-nOYu3WL1oGs_Gkar0gArIJEC0VqqqmMLl0"

hostname: "localhost"
