---
- name: Include nginx role
  tags: conf
  ansible.builtin.import_role:
    role: nginxinc.nginx
  vars:
    nginx_start: false

- name: Remove nginx default configuration
  tags: conf
  ansible.builtin.file:
    path: /etc/nginx/conf.d/default.conf
    state: absent

- name: Deploy nginx configurations
  tags: conf
  notify: Restart nginx
  ansible.builtin.template:
    src: upstream.conf.j2
    dest: "/etc/nginx/conf.d/{{ item.name }}.conf"
    owner: root
    group: root
    mode: "0600"
  loop: "{{ nginx_reverse_proxy_upstreams }}"
  loop_control:
    label: "{{ item.name }}"
