name: Enforce linter
on: [push]

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v4
      -
        name: Restore cache
        id: cache
        uses: actions/cache@v4
        with:
          path: |
            ./venv
            ~/.gitconfig
            ~/.ansible/roles
          key: ${{ runner.os }}-ansible-cache
      -
        name: Install dependencies
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install ansible ansible-lint ansible-playbook-grapher
          ansible-galaxy install -r requirements.yaml
      -
        name: Ensure the linter passes
        run: |
          source venv/bin/activate
          ansible-lint \
            --exclude .github/ roles/geerlingguy.mysql/ \
            --profile production \
            --offline \
            -qq

