name: Update profile readme with up-to-date infrastructure
on: [push]

jobs:
  Build-Graph:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v4

      -
        name: Checkout profile readme
        uses: actions/checkout@v4
        with:
          repository: '${{ github.actor }}/${{ github.actor }}'
          ref: 'main'
          path: ./profile_repo
          token: ${{ secrets.GIT_TOKEN }}

      
      - name: Restore cached venv and git configuration
        id: cache-restore
        uses: actions/cache/restore@v4
        with:
          path: |
            ./venv
            ~/.gitconfig
          key: ${{ runner.os }}-ansible-graph-cache

      -
        name: Install dependencies
        if: steps.cache-restore.outputs.cache-hit != 'true'
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install ansible
          pip install ansible-playbook-grapher

      -
        name: Configure git
        if: steps.cache-restore.outputs.cache-hit != 'true'
        run: |
          git config --global user.email "action@git.ea.hub"
          git config --global user.name "Action"
          git config --global credential.helper '!f() { sleep 1; echo "username=${{ github.actor }} token=${{ secrets.GIT_TOKEN }}"; }; f'
      
      -
        name: Generate graph
        run: |
          source venv/bin/activate
          ansible-playbook-grapher \
            --title "My super-well-designed Ansible mess" \
            --renderer mermaid-flowchart \
            --only-roles \
            -i ./inventory.yaml \
            -o ./graph \
            ./playbook.yaml
      
      -
        name: Update profile graph
        run: |
          cd profile_repo
          cat template/README.md > README.md
          echo '```mermaid' >> README.md
          cat graph.mmd >> README.md
          echo '```' >> README.md

          git add README.md
          git commit -m 'profile graph automatic update'
          git push

      - name: Save venv and git configuration
        id: cache-save
        uses: actions/cache/save@v4
        with:
          path: |
            ./venv
            ~/.gitconfig
          key: ${{ steps.cache-restore.outputs.cache-primary-key }}
