name: Update profile readme with up-to-date infrastructure ${{ github.actor }}
on: [push]

jobs:
  Build-Graph:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v4

      -
        name: Checkout profile readme
        uses: actions/checkout@v4
        with:
          repository: '${{ github.actor }}/.github'
          ref: 'main'
          path: ./profile_repo
          token: ${{ secrets.GIT_TOKEN }}

      -
        name: Install dependencies
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install ansible
          pip install ansible-playbook-grapher
      
      -
        name: Generate graph
        run: |
          source venv/bin/activate
          ansible-playbook-grapher \
            --title "My super-well-designed Ansible mess" \
            --renderer mermaid-flowchart \
            --only-roles \
            -i ./inventory.yaml \
            -o ./graph \
            ./playbook.yaml
      
      -
        name: Update profile graph
        run: |
          cat profile_repo/README.md > profile_repo/profile/README.md
          echo '```mermaid' >> profile_repo/profile/README.md
          cat graph.mmd >> profile_repo/profile/README.md
          echo '```' >> profile_repo/profile/README.md
          cd profile_repo

          git config --global user.email "action@git.ea.hub"
          git config --global user.name "Action"
          git config --global credential.helper '!f() { sleep 1; echo "username=${{ github.actor }} token=${{ secrets.GIT_TOKEN }}"; }; f'

          git add profile/README.md
          git commit -m 'profile graph automatic update'
          # git -c http.extraHeader="Authorization: Basic `base64 ${{ github.actor }}:${{ secrets.GIT_TOKEN }}`"
          git push

